# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'PerformanceAnalyzer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PerformanceAnalyzer
  pod 'PureLayout', '~> 3.0.2'
  pod 'fishhook', '~> 0.2'
end

target 'AnalyzerCFunction' do
    use_frameworks!
    pod 'fishhook', '~> 0.2'

end
